/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class AdornerDecorator : Decorator {

  internal AdornerDecorator(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.AdornerDecorator_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(AdornerDecorator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public AdornerDecorator(bool logicalChild) : this(NoesisGUI_PINVOKE.new_AdornerDecorator__SWIG_0(logicalChild), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public AdornerDecorator() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(AdornerDecorator)) {
      return NoesisGUI_PINVOKE.new_AdornerDecorator__SWIG_1();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public void AddLayer(Visual layerRoot) {
    NoesisGUI_PINVOKE.AdornerDecorator_AddLayer(swigCPtr, Visual.getCPtr(layerRoot));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public void RemoveLayer(Visual layerRoot) {
    NoesisGUI_PINVOKE.AdornerDecorator_RemoveLayer(swigCPtr, Visual.getCPtr(layerRoot));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.AdornerDecorator_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

