/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class BaseExpression : BaseComponent {

  internal BaseExpression(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.BaseExpression_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(BaseExpression obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected BaseExpression() {
  }

  public EvaluateBehavior GetEvaluateBehavior() {
    EvaluateBehavior ret = (EvaluateBehavior)NoesisGUI_PINVOKE.BaseExpression_GetEvaluateBehavior(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

