/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public partial class DependencyProperty : BaseComponent {

  internal DependencyProperty(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.DependencyProperty_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(DependencyProperty obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected DependencyProperty() {
  }

  public static object GetUnsetValue() {
    IntPtr cPtr = NoesisGUI_PINVOKE.DependencyProperty_GetUnsetValue();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return Noesis.Extend.Unbox(Noesis.Extend.GetProxy(cPtr, false));
}

  public string GetName() {
    string ret = NoesisGUI_PINVOKE.DependencyProperty_GetName(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool IsReadOnly() {
    bool ret = NoesisGUI_PINVOKE.DependencyProperty_IsReadOnly(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public uint GetSize() {
    uint ret = NoesisGUI_PINVOKE.DependencyProperty_GetSize(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public virtual void ClearAnimation(DependencyObject obj) {
    NoesisGUI_PINVOKE.DependencyProperty_ClearAnimation(swigCPtr, DependencyObject.getCPtr(obj));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public virtual void CoerceValue(DependencyObject obj) {
    NoesisGUI_PINVOKE.DependencyProperty_CoerceValue(swigCPtr, DependencyObject.getCPtr(obj));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public void SetIsReadOnly(bool value) {
    NoesisGUI_PINVOKE.DependencyProperty_SetIsReadOnly(swigCPtr, value);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public void AddMetaData(PropertyMetadata metaData) {
    NoesisGUI_PINVOKE.DependencyProperty_AddMetaData__SWIG_0(swigCPtr, PropertyMetadata.getCPtr(metaData));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

}

}

