/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class EventTrigger : TriggerBase {

  internal EventTrigger(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.EventTrigger_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(EventTrigger obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public EventTrigger() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(EventTrigger)) {
      return NoesisGUI_PINVOKE.new_EventTrigger();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public TriggerActionCollection Actions {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.EventTrigger_Actions_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return Noesis.Extend.GetProxy(cPtr, false) as TriggerActionCollection;
    }
  
  }

  public RoutedEvent RoutedEvent {
    set {
      NoesisGUI_PINVOKE.EventTrigger_RoutedEvent_set(swigCPtr, RoutedEvent.getCPtr(value));
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    } 
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.EventTrigger_RoutedEvent_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return Noesis.Extend.GetProxy(cPtr, false) as RoutedEvent;
    }
  
  }

  public string SourceName {
  set {
    NoesisGUI_PINVOKE.EventTrigger_SourceName_set(swigCPtr, value != null ? value : string.Empty);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
  }

  get {
    string ret = NoesisGUI_PINVOKE.EventTrigger_SourceName_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    return ret;
  }

  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.EventTrigger_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

