/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public partial class FrameworkPropertyMetadata : UIPropertyMetadata {

  internal FrameworkPropertyMetadata(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.FrameworkPropertyMetadata_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(FrameworkPropertyMetadata obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public FrameworkPropertyMetadata() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(FrameworkPropertyMetadata)) {
      return NoesisGUI_PINVOKE.new_FrameworkPropertyMetadata__SWIG_0();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public FrameworkPropertyMetadata(int options) : this(NoesisGUI_PINVOKE.new_FrameworkPropertyMetadata__SWIG_1(options), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public bool AffectsMeasure() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsMeasure(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool AffectsArrange() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsArrange(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool AffectsParentMeasure() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsParentMeasure(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool AffectsParentArrange() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsParentArrange(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool AffectsRender() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsRender(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool Inherits() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_Inherits(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool OverridesInheritanceBehavior() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_OverridesInheritanceBehavior(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool IsNotDataBindable() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_IsNotDataBindable(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool BindsTwoWayByDefault() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_BindsTwoWayByDefault(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public UpdateSourceTrigger DefaultUpdateSourceTrigger() {
    UpdateSourceTrigger ret = (UpdateSourceTrigger)NoesisGUI_PINVOKE.FrameworkPropertyMetadata_DefaultUpdateSourceTrigger(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public bool SubPropertiesDoNotAffectRender() {
    bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_SubPropertiesDoNotAffectRender(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public override void ClearInheritedValues() {
    NoesisGUI_PINVOKE.FrameworkPropertyMetadata_ClearInheritedValues(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public override void Merge(PropertyMetadata ancestor) {
    NoesisGUI_PINVOKE.FrameworkPropertyMetadata_Merge(swigCPtr, PropertyMetadata.getCPtr(ancestor));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

}

}

