/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class KeyGesture : InputGesture {

  internal KeyGesture(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.KeyGesture_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(KeyGesture obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public KeyGesture() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(KeyGesture)) {
      return NoesisGUI_PINVOKE.new_KeyGesture__SWIG_0();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public KeyGesture(uint key, uint modifiers) : this(NoesisGUI_PINVOKE.new_KeyGesture__SWIG_1(key, modifiers), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public KeyGesture(uint key) : this(NoesisGUI_PINVOKE.new_KeyGesture__SWIG_2(key), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public override bool Matches(object target, RoutedEventArgs args) {
    bool ret = NoesisGUI_PINVOKE.KeyGesture_Matches(swigCPtr, Noesis.Extend.GetInstanceHandle(target), RoutedEventArgs.getCPtr(args));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public uint Key {
    get {
      uint ret = NoesisGUI_PINVOKE.KeyGesture_Key_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  public uint Modifiers {
    get {
      uint ret = NoesisGUI_PINVOKE.KeyGesture_Modifiers_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  public string DisplayString {
  get {
    string ret = NoesisGUI_PINVOKE.KeyGesture_DisplayString_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    return ret;
  }

  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.KeyGesture_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

