/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ListBoxItem : ContentControl {

  internal ListBoxItem(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.ListBoxItem_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(ListBoxItem obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }


  public delegate void SelectedHandler(object sender, RoutedEventArgs e);
  public event SelectedHandler Selected {
    add {
      if (!_Selected.ContainsKey(swigCPtr.Handle)) {
        _Selected.Add(swigCPtr.Handle, null);

        NoesisGUI_PINVOKE.BindEvent_ListBoxItem_Selected(_raiseSelected, swigCPtr.Handle);
        #if UNITY_EDITOR || NOESIS_API
        if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
        #endif
      }

      _Selected[swigCPtr.Handle] += value;
    }
    remove {
      if (!_Selected.ContainsKey(swigCPtr.Handle)) {
        throw new System.Exception("Delegate not found");
      }

      _Selected[swigCPtr.Handle] -= value;

      if (_Selected[swigCPtr.Handle] == null) {
        NoesisGUI_PINVOKE.UnbindEvent_ListBoxItem_Selected(_raiseSelected, swigCPtr.Handle);
        #if UNITY_EDITOR || NOESIS_API
        if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
        #endif

        _Selected.Remove(swigCPtr.Handle);
      }
    }
  }

  internal delegate void RaiseSelectedCallback(IntPtr cPtr, IntPtr sender, IntPtr e);
  private static RaiseSelectedCallback _raiseSelected = RaiseSelected;

  [MonoPInvokeCallback(typeof(RaiseSelectedCallback))]
  private static void RaiseSelected(IntPtr cPtr, IntPtr sender, IntPtr e) {
    if (!_Selected.ContainsKey(cPtr)) {
      throw new System.Exception("Delegate not found");
    }
    if (sender == System.IntPtr.Zero && e == System.IntPtr.Zero) {
      _Selected.Remove(cPtr);
      return;
    }
    SelectedHandler handler = _Selected[cPtr];
    if (handler != null) {
      handler(Noesis.Extend.Unbox(Noesis.Extend.GetProxy(sender, false)), new RoutedEventArgs(e, false));
    }
  }

  static System.Collections.Generic.Dictionary<System.IntPtr, SelectedHandler> _Selected =
      new System.Collections.Generic.Dictionary<System.IntPtr, SelectedHandler>();


  public delegate void UnselectedHandler(object sender, RoutedEventArgs e);
  public event UnselectedHandler Unselected {
    add {
      if (!_Unselected.ContainsKey(swigCPtr.Handle)) {
        _Unselected.Add(swigCPtr.Handle, null);

        NoesisGUI_PINVOKE.BindEvent_ListBoxItem_Unselected(_raiseUnselected, swigCPtr.Handle);
        #if UNITY_EDITOR || NOESIS_API
        if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
        #endif
      }

      _Unselected[swigCPtr.Handle] += value;
    }
    remove {
      if (!_Unselected.ContainsKey(swigCPtr.Handle)) {
        throw new System.Exception("Delegate not found");
      }

      _Unselected[swigCPtr.Handle] -= value;

      if (_Unselected[swigCPtr.Handle] == null) {
        NoesisGUI_PINVOKE.UnbindEvent_ListBoxItem_Unselected(_raiseUnselected, swigCPtr.Handle);
        #if UNITY_EDITOR || NOESIS_API
        if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
        #endif

        _Unselected.Remove(swigCPtr.Handle);
      }
    }
  }

  internal delegate void RaiseUnselectedCallback(IntPtr cPtr, IntPtr sender, IntPtr e);
  private static RaiseUnselectedCallback _raiseUnselected = RaiseUnselected;

  [MonoPInvokeCallback(typeof(RaiseUnselectedCallback))]
  private static void RaiseUnselected(IntPtr cPtr, IntPtr sender, IntPtr e) {
    if (!_Unselected.ContainsKey(cPtr)) {
      throw new System.Exception("Delegate not found");
    }
    if (sender == System.IntPtr.Zero && e == System.IntPtr.Zero) {
      _Unselected.Remove(cPtr);
      return;
    }
    UnselectedHandler handler = _Unselected[cPtr];
    if (handler != null) {
      handler(Noesis.Extend.Unbox(Noesis.Extend.GetProxy(sender, false)), new RoutedEventArgs(e, false));
    }
  }

  static System.Collections.Generic.Dictionary<System.IntPtr, UnselectedHandler> _Unselected =
      new System.Collections.Generic.Dictionary<System.IntPtr, UnselectedHandler>();


  public ListBoxItem() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(ListBoxItem)) {
      return NoesisGUI_PINVOKE.new_ListBoxItem();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public static DependencyProperty IsSelectedProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ListBoxItem_IsSelectedProperty_get();
      DependencyProperty ret = (cPtr == IntPtr.Zero) ? null : new DependencyProperty(cPtr, false);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  public bool IsSelected {
    set {
      NoesisGUI_PINVOKE.ListBoxItem_IsSelected_set(swigCPtr, value);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    } 
    get {
      bool ret = NoesisGUI_PINVOKE.ListBoxItem_IsSelected_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ListBoxItem_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }


  internal new static IntPtr Extend(System.Type type) {
    IntPtr unityType = Noesis.Extend.GetPtrForType(type);
    IntPtr nativeType = NoesisGUI_PINVOKE.Extend_ListBoxItem(unityType);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return nativeType;
  }
}

}

