/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ParallelTimeline : TimelineGroup {

  internal ParallelTimeline(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.ParallelTimeline_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(ParallelTimeline obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public ParallelTimeline() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(ParallelTimeline)) {
      return NoesisGUI_PINVOKE.new_ParallelTimeline();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public static DependencyProperty SlipBehaviorProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ParallelTimeline_SlipBehaviorProperty_get();
      DependencyProperty ret = (cPtr == IntPtr.Zero) ? null : new DependencyProperty(cPtr, false);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  public SlipBehavior SlipBehavior {
    set {
      NoesisGUI_PINVOKE.ParallelTimeline_SlipBehavior_set(swigCPtr, (int)value);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    } 
    get {
      SlipBehavior ret = (SlipBehavior)NoesisGUI_PINVOKE.ParallelTimeline_SlipBehavior_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ParallelTimeline_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

