/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class PointAnimationUsingKeyFrames : AnimationTimeline {

  internal PointAnimationUsingKeyFrames(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.PointAnimationUsingKeyFrames_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(PointAnimationUsingKeyFrames obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public PointAnimationUsingKeyFrames() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(PointAnimationUsingKeyFrames)) {
      return NoesisGUI_PINVOKE.new_PointAnimationUsingKeyFrames();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public PointKeyFrameCollection KeyFrames {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.PointAnimationUsingKeyFrames_KeyFrames_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return Noesis.Extend.GetProxy(cPtr, false) as PointKeyFrameCollection;
    }
  
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PointAnimationUsingKeyFrames_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

