/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class PropertyPath : BaseComponent {

  internal PropertyPath(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.PropertyPath_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(PropertyPath obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public PropertyPath() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(PropertyPath)) {
      return NoesisGUI_PINVOKE.new_PropertyPath__SWIG_0();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public PropertyPath(string str) : this(NoesisGUI_PINVOKE.new_PropertyPath__SWIG_1(str != null ? str : string.Empty), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public PropertyPath(DependencyProperty dp) : this(NoesisGUI_PINVOKE.new_PropertyPath__SWIG_2(DependencyProperty.getCPtr(dp)), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public string Path {
  set {
    NoesisGUI_PINVOKE.PropertyPath_Path_set(swigCPtr, value != null ? value : string.Empty);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
  }

  get {
    string ret = NoesisGUI_PINVOKE.PropertyPath_Path_get(swigCPtr);
      #if UNITY_EDITOR || NOESIS_API
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    return ret;
  }

  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PropertyPath_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

