/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ViewBase : DependencyObject {

  internal ViewBase(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.ViewBase_SWIGUpcast(cPtr), cMemoryOwn) {
  }

  internal static HandleRef getCPtr(ViewBase obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public ViewBase() {
  }

  protected override System.IntPtr CreateCPtr(System.Type type) {
    if (type == typeof(ViewBase)) {
      return NoesisGUI_PINVOKE.new_ViewBase();
    }
    else {
      return base.CreateCPtr(type);
    }
  }

  public virtual void ClearItem(ListViewItem item) {
    NoesisGUI_PINVOKE.ViewBase_ClearItem(swigCPtr, ListViewItem.getCPtr(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public virtual void PrepareItem(ListViewItem item) {
    NoesisGUI_PINVOKE.ViewBase_PrepareItem(swigCPtr, ListViewItem.getCPtr(item));
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ViewBase_GetStaticType();
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

}

}

