using UnityEditor;
using UnityEngine;
using Noesis;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Globalization;
using System.Reflection;


public class NoesisSettings : EditorWindow
{
    public static string[] ActivePlatforms
    {
        get
        {
            var platforms = new List<string>();
            int mask = ReadSettings();

            if ((mask & DX9Platform) > 0)
            {
                platforms.Add("dx9");
            }

            if ((mask & DX11Platform) > 0)
            {
                platforms.Add("dx11");
            }

            if ((mask & GLPlatform) > 0)
            {
                platforms.Add("gl");
            }

            if ((mask & IOSPlatform) > 0)
            {
                platforms.Add("ios");
            }

            if ((mask & AndroidPlatform) > 0)
            {
                platforms.Add("android");
            }

            return platforms.ToArray();
        }
    }

    public static void RebuildActivePlatforms()
    {
        BuildToolKernel.BuildBegin();
        BuildToolKernel.Clean();

        foreach (string platform in ActivePlatforms)
        {
            Build(platform);
        }
    }

    public static void ClearLog()
    {
        Assembly assembly = Assembly.GetAssembly(typeof(SceneView));
        System.Type type = assembly.GetType("UnityEditorInternal.LogEntries");
        MethodInfo method = type.GetMethod("Clear");
        method.Invoke(new object(), null);
    }

    private static int DX9Platform = 1;
    private static int GLPlatform = 2;
    private static int IOSPlatform = 4;
    private static int AndroidPlatform = 8;
    private static int DX11Platform = 16;

    private static string DX9Field = "NoesisDX9";
    private static string DX11Field = "NoesisDX11";
    private static string GLField = "NoesisGL";
    private static string AndroidField = "NoesisAndroid";
    private static string IOSField = "NoesisIOS";
    
    private static int ReadSettings()
    {
        int activePlatforms = 0;

        bool isWindows = UnityEngine.Application.platform == UnityEngine.RuntimePlatform.WindowsEditor;
        bool isOSX = !isWindows;

        if (PlayerPrefs.GetInt(DX9Field, 0) > 0)
        {
            activePlatforms |= DX9Platform;
        }

        if (PlayerPrefs.GetInt(DX11Field, isWindows ? 1 : 0) > 0)
        {
            activePlatforms |= DX11Platform;
        }

        if (PlayerPrefs.GetInt(GLField, isOSX ? 1 : 0) > 0)
        {
            activePlatforms |= GLPlatform;
        }

        if (PlayerPrefs.GetInt(IOSField, 0) > 0)
        {
            activePlatforms |= IOSPlatform;
        }

        if (PlayerPrefs.GetInt(AndroidField, 0) > 0)
        {
            activePlatforms |= AndroidPlatform;
        }

        return activePlatforms;
    }

    private static void WriteSettings(int activePlatforms)
    {
        PlayerPrefs.SetInt(DX9Field, (activePlatforms & DX9Platform) > 0 ? 1 : 0);
        PlayerPrefs.SetInt(DX11Field, (activePlatforms & DX11Platform) > 0 ? 1 : 0);
        PlayerPrefs.SetInt(GLField, (activePlatforms & GLPlatform) > 0 ? 1 : 0);
        PlayerPrefs.SetInt(IOSField, (activePlatforms & IOSPlatform) > 0 ? 1 : 0);
        PlayerPrefs.SetInt(AndroidField, (activePlatforms & AndroidPlatform) > 0 ? 1 : 0);
        PlayerPrefs.Save();

        using (StreamWriter file = new StreamWriter(UnityEngine.Application.dataPath + "/Editor/NoesisGUI/Platform_.cs"))
        {
            file.WriteLine("// This file is automatically generated");
            file.WriteLine();

            if ((activePlatforms & DX9Platform) == 0 && (activePlatforms & DX11Platform) == 0)
            {
                file.WriteLine("#if UNITY_STANDALONE_WIN");
                file.WriteLine("#    error DirectX is not active! Please, activate it in Tools -> NoesisGUI -> Settings");
                file.WriteLine("#endif");
            }

            if ((activePlatforms & GLPlatform) == 0)
            {
                file.WriteLine("#if UNITY_STANDALONE_OSX");
                file.WriteLine("#    error GL is not active! Please, activate it in Tools -> NoesisGUI -> Settings");
                file.WriteLine("#endif");
            }

            if ((activePlatforms & IOSPlatform) == 0)
            {
                file.WriteLine("#if UNITY_IPHONE");
                file.WriteLine("#    error iOS is not active! Please, activate it in Tools -> NoesisGUI -> Settings");
                file.WriteLine("#endif");
            }

            if ((activePlatforms & AndroidPlatform) == 0)
            {
                file.WriteLine("#if UNITY_ANDROID");
                file.WriteLine("#    error Android is not active! Please, activate it in Tools -> NoesisGUI -> Settings");
                file.WriteLine("#endif");
            }
        }

        AssetDatabase.ImportAsset("Assets/Editor/NoesisGUI/Platform_.cs");
    }

    private int activePlatforms_;
    
    [UnityEditor.MenuItem("Tools/NoesisGUI/Settings", false, 30000)]
    static void ShowWindow()
    {
        EditorWindow window = GetWindow(typeof(NoesisSettings), false, "NoesisGUI");
        window.Show();
    }

    [UnityEditor.MenuItem("Tools/NoesisGUI/Unity Tutorial", false, 30011)]
    static void OpenUnityTutorial()
    {
        UnityEngine.Application.OpenURL("file://" + UnityEngine.Application.dataPath +
            "/NoesisGUI/Docs/Gui.Core.Unity3DTutorial.html");
    }

    [UnityEditor.MenuItem("Tools/NoesisGUI/Video Tutorial", false, 30012)]
    static void OpenVideoTutorial()
    {
        UnityEngine.Application.OpenURL("https://vimeo.com/102469656");
    }

    [UnityEditor.MenuItem("Tools/NoesisGUI/Documentation", false, 30013)]
    static void OpenDocumentation()
    {
        UnityEngine.Application.OpenURL("file://" + UnityEngine.Application.dataPath +
            "/NoesisGUI/index.html");
    }

    [UnityEditor.MenuItem("Tools/NoesisGUI/Forums", false, 30014)]
    static void OpenForum()
    {
        UnityEngine.Application.OpenURL("http://forums.noesisengine.com/");
    }

    [UnityEditor.MenuItem("Tools/NoesisGUI/Release Notes", false, 30050)]
    static void OpenReleaseNotes()
    {
        UnityEngine.Application.OpenURL("http://www.noesisengine.com/forums/viewtopic.php?f=3&t=91");
    }

    [UnityEditor.MenuItem("Tools/NoesisGUI/Report a bug", false, 30051)]
    static void OpenReportBug()
    {
        UnityEngine.Application.OpenURL("http://bugs.noesisengine.com/");
    }

    void Awake()
    {
        activePlatforms_ = ReadSettings();
    }
        
    void OnGUI()
    {
        bool isCompiling = EditorApplication.isCompiling;
        GUI.enabled = !isCompiling;

        GUIStyle titleStyle = new GUIStyle(EditorStyles.whiteLabel);
        titleStyle.alignment = TextAnchor.MiddleCenter;
        titleStyle.fontStyle = UnityEngine.FontStyle.Bold;
        titleStyle.fontSize = 12;
        GUILayout.Label("NoesisGUI Settings", titleStyle);
        GUILayout.Label("Build Platforms", EditorStyles.boldLabel);

        int activePlatforms = 0;
        int numActivePlatforms = 0;

        GUILayout.BeginHorizontal();

        bool isWindows = UnityEngine.Application.platform == UnityEngine.RuntimePlatform.WindowsEditor;
        if (!isWindows)
        {
            GUI.enabled = false;
        }

        if (GUILayout.Toggle((activePlatforms_ & DX9Platform) > 0, "DX9"))
        {
            activePlatforms |= DX9Platform;
            numActivePlatforms++;
        }
        if (GUILayout.Toggle((activePlatforms_ & DX11Platform) > 0, "DX11"))
        {
            activePlatforms |= DX11Platform;
            numActivePlatforms++;
        }

        GUI.enabled = !isCompiling;
        if (GUILayout.Toggle((activePlatforms_ & GLPlatform) > 0, "GL"))
        {
            activePlatforms |= GLPlatform;
            numActivePlatforms++;
        }

        if (GUILayout.Toggle((activePlatforms_ & IOSPlatform) > 0, "iOS"))
        {
            activePlatforms |= IOSPlatform;
            numActivePlatforms++;
        }

        if (GUILayout.Toggle((activePlatforms_ & AndroidPlatform) > 0, "Android"))
        {
            activePlatforms |= AndroidPlatform;
            numActivePlatforms++;
        }
        GUILayout.EndHorizontal();

        int delta = activePlatforms ^ activePlatforms_;
        if (delta > 0)
        {
            activePlatforms_ = activePlatforms;
            WriteSettings(activePlatforms_);
        }

        GUILayout.Space(15.0f);
        GUILayout.BeginHorizontal();
        GUILayout.FlexibleSpace();
        
        if (GUILayout.Button(isCompiling ? "Unity is compiling scripts..." : "Rebuild", GUILayout.MinWidth(100)))
        {
            try
            {
                ClearLog();

                int numXAMLs = Directory.GetFiles(UnityEngine.Application.dataPath, "*.xaml", SearchOption.AllDirectories).Length;
                string platform = "";
                float platformProgress = 0.0f;
                float platformDelta = 1.0f / (numXAMLs * (numActivePlatforms + 1));
                float progress = 0.0f;
                float deltaProgress = 1.0f / (numActivePlatforms + 1);

                EditorUtility.DisplayProgressBar("Building Resources", "Cleaning...", 0.0f);
                BuildToolKernel.BuildBegin();
                BuildToolKernel.Clean();

                Action<String> action = s =>
                {
                    EditorUtility.DisplayProgressBar("Building " + platform, s + "...", progress + platformProgress);
                    platformProgress = Math.Min(platformProgress + platformDelta, deltaProgress);
                };
                BuildToolKernel.BuildEvent += action;

                if ((activePlatforms_ & DX9Platform) > 0)
                {
                    platformProgress = 0.0f;
                    progress += deltaProgress;
                    platform = "DirectX 9";
                    Build("dx9");
                }

                if ((activePlatforms_ & DX11Platform) > 0)
                {
                    platformProgress = 0.0f;
                    progress += deltaProgress;
                    platform = "DirectX 11";
                    Build("dx11");
                }

                if ((activePlatforms_ & GLPlatform) > 0)
                {
                    platformProgress = 0.0f;
                    progress += deltaProgress;
                    platform = "OpenGL";
                    Build("gl");
                }

                if ((activePlatforms_ & IOSPlatform) > 0)
                {
                    platformProgress = 0.0f;
                    progress += deltaProgress;
                    platform = "iOS";
                    Build("ios");
                }

                if ((activePlatforms_ & AndroidPlatform) > 0)
                {
                    platformProgress = 0.0f;
                    progress += deltaProgress;
                    platform = "Android";
                    Build("android");
                }

                BuildToolKernel.BuildEvent -= action;
                EditorUtility.DisplayProgressBar("Building Resources", "", 1.0f);
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }
        }

        GUILayout.FlexibleSpace();
        GUILayout.EndHorizontal();
        GUI.enabled = true;
    }
   
    private static void Build(string platform)
    {
        using (BuildToolKernel builder = new BuildToolKernel(platform))
        {
            builder.BuildAll();
        }
    }
}
